# Generated by Django 5.2.17 on 2026-09-10 01:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Preferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("widgets", models.JSONField(default=dict)),
                ("notifications_read", models.BooleanField(default=False)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("credit_cards", "Cartão"),
                            ("vehicles", "Veículo"),
                            ("trips", "Viagem"),
                            ("fixed_expenses", "Despesa fixa"),
                            ("fixed_incomes", "Receita fixa"),
                            ("reserves", "Reserva"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("subtitle", models.CharField(blank=True, max_length=120)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "target",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("blue", "Azul"),
                            ("purple", "Roxo"),
                            ("green", "Verde"),
                            ("orange", "Laranja"),
                        ],
                        default="blue",
                        max_length=12,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["owner", "kind"], name="finance_por_owner_i_fdc856_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0), ("target__gte", 0)),
                        name="portfolio_nonnegative_amounts",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(max_length=120)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator("0.01")],
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("income", "Receita"), ("expense", "Despesa")], max_length=7
                    ),
                ),
                ("category", models.CharField(max_length=40)),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("paid", "Concluído"), ("pending", "Pendente")],
                        default="paid",
                        max_length=7,
                    ),
                ),
                ("account", models.CharField(default="Conta principal", max_length=60)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
                "indexes": [
                    models.Index(fields=["owner", "date"], name="finance_tra_owner_i_466876_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)), name="transaction_positive_amount"
                    )
                ],
            },
        ),
    ]
