# Generated by Django 5.2.17 on 2026-09-10 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_alter_transaction_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"kind": "vehicles"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicle_expenses",
                to="finance.portfolioitem",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("vehicle__isnull", True),
                    models.Q(
                        ("kind", "expense"),
                        ("category__in", ("IPVA", "Seguro veicular", "Combustível")),
                    ),
                    _connector="OR",
                ),
                name="vehicle_link_requires_vehicle_expense",
            ),
        ),
    ]
