# Generated by Django 5.2.17 on 2026-09-11 01:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_transaction_vehicle_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_id", models.UUIDField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("kind", models.CharField(max_length=20)),
                ("currency", models.CharField(max_length=3)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=18, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="pluggy_date",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="pluggy_id",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.bankaccount",
            ),
        ),
        migrations.CreateModel(
            name="BankConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("item_id", models.UUIDField(unique=True)),
                ("institution", models.CharField(max_length=120)),
                ("sandbox", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
                ("status", models.CharField(default="QUEUED", max_length=40)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_sync_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("sync_message", models.CharField(blank=True, max_length=250)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="finance.bankconnection",
            ),
        ),
        migrations.CreateModel(
            name="OpenFinanceIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "client_user_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
