# Generated by Django 5.2.17 on 2026-09-11 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_bankaccount_transaction_pluggy_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="category_locked",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="review_role",
            field=models.CharField(
                choices=[
                    ("normal", "Incluída nos totais"),
                    ("duplicate", "Duplicata conciliada"),
                    ("transfer", "Transferência interna"),
                ],
                default="normal",
                editable=False,
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name="CategoryRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("match_text", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[("income", "Receita"), ("expense", "Despesa")], max_length=7
                    ),
                ),
                ("category", models.CharField(max_length=40)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.portfolioitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "match_text", "kind"), name="unique_category_rule"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReviewDismissal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("duplicate", "Duplicata"), ("transfer", "Transferência interna")],
                        max_length=12,
                    ),
                ),
                (
                    "first",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dismissals_first",
                        to="finance.transaction",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "second",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dismissals_second",
                        to="finance.transaction",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("first", "second", "kind"), name="unique_review_dismissal"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReviewPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("duplicate", "Duplicata"), ("transfer", "Transferência interna")],
                        max_length=12,
                    ),
                ),
                (
                    "first",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_as_first",
                        to="finance.transaction",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "second",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_as_second",
                        to="finance.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("first", models.F("second")), _negated=True),
                        name="review_pair_distinct_records",
                    )
                ],
            },
        ),
    ]
